spring:
  application:
    name: diplomayin-java
  datasource:
    url: jdbc:postgresql://localhost:5432/java
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/liquibase-changelog.yaml
    enabled: true
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}

    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

server:
  port: 7404
  address: 0.0.0.0  # Слушать на всех интерфейсах для сетевого доступа

hr:
  cors:
    origins: http://localhost:4200

jwt:
  secret: 21321380832109823092382193gifdijg9df8guf9dvjfdiovmkfjeirj98ru489r4rf9ojavndzsief98erwr21

app:
  upload:
    dir: uploads

hrspace:
  browseUrl: http://localhost:4200

#  front:
#    assets: /Users/karen/Projects/hr-space/hr-space-back/hr-resources/images
#
#file:
#  upload:
#    path: /Users/karen/Projects/hr-space/hr-space-back/hr-resources/employeedocs
#
#image:
#  upload:
#    directory: "#{systemProperties['user.home']}/img/"
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#springdoc:
#  api-docs:
#    path: /employee/api-docs

#admin:
#  email: ${ADMIN_EMAIL:admin@itspace.am}
#  password: ${ADMIN_PASSWORD:admin123456}